-- SQL script to add contracts and vendors from the provided table
-- This script will create vendors and contracts with proper relationships

-- First, let's add all the vendors (contract names are vendor names)
INSERT INTO vendors (id, name, company_type, status) VALUES
(UUID(), 'CLAXON ACTUARIES', 'corporation', 'active'),
(UUID(), 'OVACODA BUSINESS SOLUTIONS', 'corporation', 'active'),
(UUID(), 'TECHSOFT TECHNOLOGIES', 'corporation', 'active'),
(UUID(), 'BAKERTILLY CHARTERED ACCOUNTANTS', 'corporation', 'active'),
(UUID(), 'HYGIENIC SERVICES', 'corporation', 'active'),
(UUID(), 'GUARD ALERT', 'corporation', 'active'),
(UUID(), 'TSEBO PVT LTD', 'corporation', 'active'),
(UUID(), 'BIRDCOCK INVESTMENTS', 'corporation', 'active'),
(UUID(), 'CITY PARKING', 'corporation', 'active'),
(UUID(), 'MINING INDUSTRY PENSION FUND', 'corporation', 'active'),
(UUID(), 'TRANSERVE', 'corporation', 'active'),
(UUID(), 'CABLESTING PVT LD', 'corporation', 'active'),
(UUID(), 'VERTICAL MOMENTUM', 'corporation', 'active'),
(UUID(), 'CREATIVE HR SOLUTIONS - PAYWELL', 'corporation', 'active'),
(UUID(), 'CLIPTAG (PVT) LTD', 'corporation', 'active'),
(UUID(), 'RADIO SOLUTIONS', 'corporation', 'active'),
(UUID(), 'SCHINDWE LIFTS', 'corporation', 'active'),
(UUID(), 'S. PATEL', 'individual', 'active'),
(UUID(), 'ADALET', 'corporation', 'active'),
(UUID(), 'POWERMEC GENERATORS', 'corporation', 'active'),
(UUID(), 'EZYTRACK (PVT) LTD', 'corporation', 'active'),
(UUID(), 'SAFEGUARD SECURITY (PVT) LTD', 'corporation', 'active'),
(UUID(), 'OMNISOL HOLDINGS', 'corporation', 'active'),
(UUID(), 'POWERTEL COMMUNICATIONS', 'corporation', 'active'),
(UUID(), 'TECHURATE', 'corporation', 'active'),
(UUID(), 'CIMETRIX SOLUTIONS (PRIVATE) LIMITED', 'corporation', 'active'),
(UUID(), 'HIT', 'corporation', 'active'),
(UUID(), 'AFROCENTRIC TECHNOLOGIES', 'corporation', 'active'),
(UUID(), 'MITRA SYSTEMS', 'corporation', 'active'),
(UUID(), 'TENDO ELCTRONICS AND ENGINEERING', 'corporation', 'active'),
(UUID(), 'NATHAN CLAIRE', 'individual', 'active'),
(UUID(), 'NIVACITY', 'corporation', 'active'),
(UUID(), 'ADVANCENET GROUP', 'corporation', 'active'),
(UUID(), 'AXXIS SYSTEMS', 'corporation', 'active'),
(UUID(), 'ADEPT SOLUTIONS', 'corporation', 'active'),
(UUID(), 'LIQUID INTELLIGENT TECH', 'corporation', 'active'),
(UUID(), 'NEW HEALTH 263', 'corporation', 'active'),
(UUID(), 'ELECTRONIC DATA INTERCHANGE SERVICES (PVT) LTD', 'corporation', 'active'),
(UUID(), 'GLOBAL HORIZONS', 'corporation', 'active'),
(UUID(), 'OMNISOL HOLDING', 'corporation', 'active'),
(UUID(), 'ICRAFT PVT LTD', 'corporation', 'active'),
(UUID(), 'KENAC COMPUTERS', 'corporation', 'active'),
(UUID(), 'EVOLVE CONSULTING', 'corporation', 'active'),
(UUID(), 'MUZANGAZA ATTORNEYS', 'corporation', 'active'),
(UUID(), 'BHATASARA ATTORNEYS', 'corporation', 'active'),
(UUID(), 'CITY OF BULAWAYO', 'government', 'active'),
(UUID(), 'SAMURIWO ATTORNEYS', 'corporation', 'active'),
(UUID(), 'JOHN HOKINS HEALTHCARE', 'corporation', 'active'),
(UUID(), 'B. BRAUN ZIMBABWE', 'corporation', 'active'),
(UUID(), 'ASTRO TECHONOLY GROUP', 'corporation', 'active'),
(UUID(), 'MATERDEI HOSPITAL', 'corporation', 'active'),
(UUID(), 'GREENWOOD PHARMACIES', 'corporation', 'active'),
(UUID(), 'BESTZONE PHARMACY', 'corporation', 'active'),
(UUID(), 'BOOTIES PHARMACY', 'corporation', 'active'),
(UUID(), 'MEDORANGE PHARMACIES', 'corporation', 'active'),
(UUID(), 'DISCOVERY AMBULANCES', 'corporation', 'active'),
(UUID(), 'CHACKSEN CLEANING', 'corporation', 'active'),
(UUID(), 'LINDA BANDA ATTORNEYS', 'corporation', 'active'),
(UUID(), 'CADCRAFT TRADING (PRIVATE) LIMITED', 'corporation', 'active'),
(UUID(), 'ANGWISPER ENTERPRISES (PRIVATE) LIMITED', 'corporation', 'active'),
(UUID(), 'NEMCHEM INTERNATIONAL (PRIVATE) LIMITED', 'corporation', 'active'),
(UUID(), 'HURUNGWE RDC', 'government', 'active'),
(UUID(), 'ZUZE LAW CHAMBERS', 'corporation', 'active'),
(UUID(), 'VICEMODE INVESTMENTS', 'corporation', 'active'),
(UUID(), 'MACRO-CENTURY (PRIVATE) LIMITED', 'corporation', 'active'),
(UUID(), 'ZIMBABWE UNION FOR JOURNALISTS', 'corporation', 'active'),
(UUID(), 'VPCG MOBILE', 'corporation', 'active'),
(UUID(), 'MUNNEX LANDSCAPPING', 'corporation', 'active'),
(UUID(), 'HIGHMEL SERVICES', 'corporation', 'active'),
(UUID(), 'PEACE SECURITY', 'corporation', 'active'),
(UUID(), 'PARAGON', 'corporation', 'active'),
(UUID(), 'CARDPRO', 'corporation', 'active'),
(UUID(), 'CONCORD HARDWARE CONSTRUCTION/HERBET AND BROTHERS TRANSPORT', 'corporation', 'active'),
(UUID(), 'ACFD', 'corporation', 'active'),
(UUID(), 'BEST MULTI-PURPOSE CO-OPERATION', 'corporation', 'active'),
(UUID(), 'CHRIST MINISTRIES HIGH SCHOOL', 'corporation', 'active'),
(UUID(), 'ZIMBABWE WOMENS MICROFINANCE BANK', 'corporation', 'active'),
(UUID(), 'Frolgate Technology (Private) Limited', 'corporation', 'active'),
(UUID(), 'NASHUA', 'corporation', 'active'),
(UUID(), 'CONSUMER FEEDBACK CONSULTANCY', 'corporation', 'active'),
(UUID(), 'ZB LIFE ASSURANCE LIMITED', 'corporation', 'active'),
(UUID(), 'ZB LIFE ASSURANCE', 'corporation', 'active')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- Get the Service Agreement contract type ID (create if doesn't exist)
INSERT INTO contract_types (id, name, description, is_active) 
VALUES (UUID(), 'Service Agreement', 'General service agreements and contracts', true)
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- Get the Service Agreement contract type ID
SET @service_agreement_id = (SELECT id FROM contract_types WHERE name = 'Service Agreement' LIMIT 1);

-- Get department IDs
SET @finance_dept_id = (SELECT id FROM departments WHERE name = 'Finance Department' LIMIT 1);
SET @hr_admin_dept_id = (SELECT id FROM departments WHERE name = 'HR and Admin Department' LIMIT 1);
SET @ict_dept_id = (SELECT id FROM departments WHERE name = 'ICT Department' LIMIT 1);
SET @legal_dept_id = (SELECT id FROM departments WHERE name = 'Legal Department' LIMIT 1);
SET @managed_care_dept_id = (SELECT id FROM departments WHERE name = 'Managed Care Department' LIMIT 1);
SET @marketing_dept_id = (SELECT id FROM departments WHERE name = 'Marketing and Member Services Department' LIMIT 1);
SET @strategy_dept_id = (SELECT id FROM departments WHERE name = 'Strategy and Research Department' LIMIT 1);

-- Now add all the contracts
INSERT INTO contracts (id, contract_number, title, description, vendor_id, contract_type_id, department_id, start_date, end_date, status) VALUES
(UUID(), 'CON-001', 'FRS-ACTURIAL SERVICES', 'FRS-ACTURIAL SERVICES', (SELECT id FROM vendors WHERE name = 'CLAXON ACTUARIES' LIMIT 1), @service_agreement_id, @finance_dept_id, '2024-10-30', '2025-04-29', 'active'),
(UUID(), 'CON-002', 'LAPTOPS SUPPLY AND DELIVERY', 'LAPTOPS SUPPLY AND DELIVERY', (SELECT id FROM vendors WHERE name = 'OVACODA BUSINESS SOLUTIONS' LIMIT 1), @service_agreement_id, @finance_dept_id, '2023-07-07', NULL, 'active'),
(UUID(), 'CON-003', 'LAPTOPS SUPPLY AND DELIVERY', 'LAPTOPS SUPPLY AND DELIVERY', (SELECT id FROM vendors WHERE name = 'TECHSOFT TECHNOLOGIES' LIMIT 1), @service_agreement_id, @finance_dept_id, '2023-06-29', '2024-06-28', 'active'),
(UUID(), 'CON-004', '2023 AUDIT SERVICES', '2023 AUDIT SERVICES', (SELECT id FROM vendors WHERE name = 'BAKERTILLY CHARTERED ACCOUNTANTS' LIMIT 1), @service_agreement_id, @finance_dept_id, '2024-10-01', NULL, 'active'),
(UUID(), 'CON-005', 'SANITARY BINS BRANCHES', 'SANITARY BINS BRANCHES', (SELECT id FROM vendors WHERE name = 'HYGIENIC SERVICES' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2024-06-30', '2026-06-29', 'active'),
(UUID(), 'CON-006', 'SECURITY SERVICES', 'SECURITY SERVICES', (SELECT id FROM vendors WHERE name = 'GUARD ALERT' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2024-12-01', '2026-11-30', 'active'),
(UUID(), 'CON-007', 'CATERING SERVICES AGREEMENT', 'CATERING SERVICES AGREEMENT', (SELECT id FROM vendors WHERE name = 'TSEBO PVT LTD' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-01-02', '2027-01-31', 'active'),
(UUID(), 'CON-008', 'CLEANING SERVICES', 'CLEANING SERVICES', (SELECT id FROM vendors WHERE name = 'BIRDCOCK INVESTMENTS' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-10-17', '2027-09-16', 'active'),
(UUID(), 'CON-009', 'PARKING BAYS RENTAL', 'PARKING BAYS RENTAL', (SELECT id FROM vendors WHERE name = 'CITY PARKING' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2024-10-01', '2027-09-30', 'active'),
(UUID(), 'CON-010', 'HWANGE LEASE ADDENDUM', 'HWANGE LEASE ADDENDUM', (SELECT id FROM vendors WHERE name = 'MINING INDUSTRY PENSION FUND' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2024-01-01', '2027-12-31', 'active'),
(UUID(), 'CON-011', 'MERCHANDIZE CREDIT FACILITY AGREEMENT', 'MERCHANDIZE CREDIT FACILITY AGREEMENT', (SELECT id FROM vendors WHERE name = 'TRANSERVE' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-01-31', '2030-01-30', 'active'),
(UUID(), 'CON-012', 'CLEANING-MASVINGO', 'CLEANING-MASVINGO', (SELECT id FROM vendors WHERE name = 'HYGIENIC SERVICES' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2024-09-04', '2026-09-03', 'active'),
(UUID(), 'CON-013', 'FIRE ALARMS EQUIPMENT', 'FIRE ALARMS EQUIPMENT', (SELECT id FROM vendors WHERE name = 'CABLESTING PVT LD' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-01-01', '2026-12-31', 'active'),
(UUID(), 'CON-014', 'STRATEGY ROLL OUT', 'STRATEGY ROLL OUT', (SELECT id FROM vendors WHERE name = 'VERTICAL MOMENTUM' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2022-01-02', '2024-03-30', 'active'),
(UUID(), 'CON-015', 'CONSULTANCY AGREEMENT', 'CONSULTANCY AGREEMENT', (SELECT id FROM vendors WHERE name = 'VERTICAL MOMENTUM' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2022-06-01', '2024-05-31', 'active'),
(UUID(), 'CON-016', 'PAYROLL LICENSING AGREEMENT', 'PAYROLL LICENSING AGREEMENT', (SELECT id FROM vendors WHERE name = 'CREATIVE HR SOLUTIONS - PAYWELL' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2020-01-01', '2024-12-31', 'active'),
(UUID(), 'CON-017', 'STORAGE/FILING SERVICES', 'STORAGE/FILING SERVICES', (SELECT id FROM vendors WHERE name = 'CLIPTAG (PVT) LTD' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2023-05-24', '2025-04-22', 'active'),
(UUID(), 'CON-018', 'SERVICE AND MAINTANCE AGREEMENT', 'SERVICE AND MAINTANCE AGREEMENT', (SELECT id FROM vendors WHERE name = 'RADIO SOLUTIONS' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2023-12-08', '2025-11-08', 'active'),
(UUID(), 'CON-019', 'MAINTANANCE AND SERVICE OF LIFTS AGREEMENT', 'MAINTANANCE AND SERVICE OF LIFTS AGREEMENT', (SELECT id FROM vendors WHERE name = 'SCHINDWE LIFTS' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-01-01', '2026-12-31', 'active'),
(UUID(), 'CON-020', 'LEASE AGREEMENT (VIC FALLS)', 'LEASE AGREEMENT (VIC FALLS)', (SELECT id FROM vendors WHERE name = 'S. PATEL' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-01-01', '2026-12-31', 'active'),
(UUID(), 'CON-021', 'FIRE FIGHTING EQUIPMENT', 'FIRE FIGHTING EQUIPMENT', (SELECT id FROM vendors WHERE name = 'ADALET' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-01-02', '2027-01-31', 'active'),
(UUID(), 'CON-022', 'GENERATOR\'S SERVICING AGREEMENT', 'GENERATOR\'S SERVICING AGREEMENT', (SELECT id FROM vendors WHERE name = 'POWERMEC GENERATORS' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2025-03-26', '2027-03-25', 'active'),
(UUID(), 'CON-023', 'VEHICLE TRACKING', 'VEHICLE TRACKING', (SELECT id FROM vendors WHERE name = 'EZYTRACK (PVT) LTD' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2024-01-02', '2026-01-31', 'active'),
(UUID(), 'CON-024', 'RAPID RESPONSE SECURITY SERVICES', 'RAPID RESPONSE SECURITY SERVICES', (SELECT id FROM vendors WHERE name = 'SAFEGUARD SECURITY (PVT) LTD' LIMIT 1), @service_agreement_id, @hr_admin_dept_id, '2024-02-26', '2026-02-25', 'active'),
(UUID(), 'CON-025', 'USD SOFTWARE DEVELOPMENT', 'USD SOFTWARE DEVELOPMENT', (SELECT id FROM vendors WHERE name = 'OMNISOL HOLDINGS' LIMIT 1), @service_agreement_id, @ict_dept_id, '2023-09-12', '2024-12-31', 'active'),
(UUID(), 'CON-026', 'DATA LINKS', 'DATA LINKS', (SELECT id FROM vendors WHERE name = 'POWERTEL COMMUNICATIONS' LIMIT 1), @service_agreement_id, @ict_dept_id, '2020-03-17', '2025-03-17', 'active'),
(UUID(), 'CON-027', 'AGREEMENT FORIMPLEMENTATION OF A MOBILE APPLICATION', 'AGREEMENT FORIMPLEMENTATION OF A MOBILE APPLICATION', (SELECT id FROM vendors WHERE name = 'TECHURATE' LIMIT 1), @service_agreement_id, @ict_dept_id, '2023-04-27', '2025-04-26', 'active'),
(UUID(), 'CON-028', 'NON-DISCLOSURE AGREEMENT', 'NON-DISCLOSURE AGREEMENT', (SELECT id FROM vendors WHERE name = 'CIMETRIX SOLUTIONS (PRIVATE) LIMITED' LIMIT 1), @service_agreement_id, @ict_dept_id, '2020-11-08', '2025-09-08', 'active'),
(UUID(), 'CON-029', 'RAPID 7 SERVICE LEVEL AGREEMENT', 'RAPID 7 SERVICE LEVEL AGREEMENT', (SELECT id FROM vendors WHERE name = 'CIMETRIX SOLUTIONS (PRIVATE) LIMITED' LIMIT 1), @service_agreement_id, @ict_dept_id, '2024-09-20', '2025-09-19', 'active'),
(UUID(), 'CON-030', 'NDA', 'NDA', (SELECT id FROM vendors WHERE name = 'HIT' LIMIT 1), @service_agreement_id, @ict_dept_id, '2024-09-28', '2025-09-27', 'active'),
(UUID(), 'CON-031', 'SOFTWARE (CORE SYSTEM)', 'SOFTWARE (CORE SYSTEM)', (SELECT id FROM vendors WHERE name = 'AFROCENTRIC TECHNOLOGIES' LIMIT 1), @service_agreement_id, @ict_dept_id, '2024-01-01', '2025-12-31', 'active'),
(UUID(), 'CON-032', 'IBM SPRECTUM PROTECT PROJECT INITIATION DOCUMENT SERVICE LEVEL AGREEMENT', 'IBM SPRECTUM PROTECT PROJECT INITIATION DOCUMENT SERVICE LEVEL AGREEMENT', (SELECT id FROM vendors WHERE name = 'MITRA SYSTEMS' LIMIT 1), @service_agreement_id, @ict_dept_id, '2023-04-06', '2026-04-05', 'active'),
(UUID(), 'CON-033', 'DATA CENTER IMPLEMENTATION SERVICE LEVEL AGREEMENT', 'DATA CENTER IMPLEMENTATION SERVICE LEVEL AGREEMENT', (SELECT id FROM vendors WHERE name = 'TENDO ELCTRONICS AND ENGINEERING' LIMIT 1), @service_agreement_id, @ict_dept_id, '2023-09-01', '2026-08-31', 'active'),
(UUID(), 'CON-034', 'APPLICATION PERFORMANCE MONITORING SYSTEM', 'APPLICATION PERFORMANCE MONITORING SYSTEM', (SELECT id FROM vendors WHERE name = 'NATHAN CLAIRE' LIMIT 1), @service_agreement_id, @ict_dept_id, '2024-01-08', '2027-01-07', 'active'),
(UUID(), 'CON-035', 'WEBSITE HOSTING SERVICES', 'WEBSITE HOSTING SERVICES', (SELECT id FROM vendors WHERE name = 'NIVACITY' LIMIT 1), @service_agreement_id, @ict_dept_id, '2024-09-01', '2027-08-31', 'active'),
(UUID(), 'CON-036', 'DOCUSIGN', 'DOCUSIGN', (SELECT id FROM vendors WHERE name = 'ADVANCENET GROUP' LIMIT 1), @service_agreement_id, @ict_dept_id, '2021-03-31', NULL, 'active'),
(UUID(), 'CON-037', 'NON-DISCLOSURE AGREEMENT', 'NON-DISCLOSURE AGREEMENT', (SELECT id FROM vendors WHERE name = 'AXXIS SYSTEMS' LIMIT 1), @service_agreement_id, @ict_dept_id, '2023-09-14', NULL, 'active'),
(UUID(), 'CON-038', 'CONSULTANCY SERVICES', 'CONSULTANCY SERVICES', (SELECT id FROM vendors WHERE name = 'ADEPT SOLUTIONS' LIMIT 1), @service_agreement_id, @ict_dept_id, '2025-03-06', NULL, 'active'),
(UUID(), 'CON-039', 'DATA LINKS AND INTERNET SERVICES', 'DATA LINKS AND INTERNET SERVICES', (SELECT id FROM vendors WHERE name = 'LIQUID INTELLIGENT TECH' LIMIT 1), @service_agreement_id, @ict_dept_id, '2014-10-14', NULL, 'active'),
(UUID(), 'CON-040', 'INFORMATION TECHNOLOGY LICENSE AND SUPPORT AGREEMENT', 'INFORMATION TECHNOLOGY LICENSE AND SUPPORT AGREEMENT', (SELECT id FROM vendors WHERE name = 'NEW HEALTH 263' LIMIT 1), @service_agreement_id, @ict_dept_id, '2019-05-01', NULL, 'active'),
(UUID(), 'CON-041', 'ODEX SOFTWARE END USER AND MAINTENANCE AGREEMENT', 'ODEX SOFTWARE END USER AND MAINTENANCE AGREEMENT', (SELECT id FROM vendors WHERE name = 'ELECTRONIC DATA INTERCHANGE SERVICES (PVT) LTD' LIMIT 1), @service_agreement_id, @ict_dept_id, '2019-11-18', NULL, 'active'),
(UUID(), 'CON-042', 'COMPUTERS SUPPLY AND DELIVERY', 'COMPUTERS SUPPLY AND DELIVERY', (SELECT id FROM vendors WHERE name = 'GLOBAL HORIZONS' LIMIT 1), @service_agreement_id, @ict_dept_id, '2024-10-17', NULL, 'active'),
(UUID(), 'CON-043', 'USD SLA', 'USD SLA', (SELECT id FROM vendors WHERE name = 'OMNISOL HOLDING' LIMIT 1), @service_agreement_id, @ict_dept_id, '2024-03-12', '2025-03-12', 'active'),
(UUID(), 'CON-044', 'MICROSOFT 365 SLA', 'MICROSOFT 365 SLA', (SELECT id FROM vendors WHERE name = 'ICRAFT PVT LTD' LIMIT 1), @service_agreement_id, @ict_dept_id, '2020-04-30', '2025-04-30', 'active'),
(UUID(), 'CON-045', 'COLOCATION SERVICES', 'COLOCATION SERVICES', (SELECT id FROM vendors WHERE name = 'KENAC COMPUTERS' LIMIT 1), @service_agreement_id, @ict_dept_id, '2025-01-01', '2027-12-31', 'active'),
(UUID(), 'CON-046', 'SAP', 'SAP', (SELECT id FROM vendors WHERE name = 'EVOLVE CONSULTING' LIMIT 1), @service_agreement_id, @ict_dept_id, '2023-07-20', '2025-06-20', 'active'),
(UUID(), 'CON-047', 'LEGAL SERVICES', 'LEGAL SERVICES', (SELECT id FROM vendors WHERE name = 'MUZANGAZA ATTORNEYS' LIMIT 1), @service_agreement_id, @legal_dept_id, '2022-04-01', '2024-03-30', 'active'),
(UUID(), 'CON-048', 'LEGAL SERVICES AGREEMENT', 'LEGAL SERVICES AGREEMENT', (SELECT id FROM vendors WHERE name = 'BHATASARA ATTORNEYS' LIMIT 1), @service_agreement_id, @legal_dept_id, '2022-04-01', '2026-02-19', 'active'),
(UUID(), 'CON-049', 'AGREEMENT OF SALE (LAND)', 'AGREEMENT OF SALE (LAND)', (SELECT id FROM vendors WHERE name = 'CITY OF BULAWAYO' LIMIT 1), @service_agreement_id, @legal_dept_id, '2023-02-21', '2027-02-20', 'active'),
(UUID(), 'CON-050', 'LEGAL SERVICES', 'LEGAL SERVICES', (SELECT id FROM vendors WHERE name = 'SAMURIWO ATTORNEYS' LIMIT 1), @service_agreement_id, @legal_dept_id, '2023-04-01', '2024-03-30', 'active'),
(UUID(), 'CON-051', 'END USER LICENSE AGREEMENT', 'END USER LICENSE AGREEMENT', (SELECT id FROM vendors WHERE name = 'JOHN HOKINS HEALTHCARE' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2019-10-01', '2024-12-30', 'active'),
(UUID(), 'CON-052', 'NON-DISCLOSURE AGREEMENT', 'NON-DISCLOSURE AGREEMENT', (SELECT id FROM vendors WHERE name = 'B. BRAUN ZIMBABWE' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2024-03-13', '2026-03-12', 'active'),
(UUID(), 'CON-053', 'NON-DISCLOSURE AGREEMENT', 'NON-DISCLOSURE AGREEMENT', (SELECT id FROM vendors WHERE name = 'ASTRO TECHONOLY GROUP' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2020-10-09', NULL, 'active'),
(UUID(), 'CON-054', 'PRE-FUNDING AGREEMENT', 'PRE-FUNDING AGREEMENT', (SELECT id FROM vendors WHERE name = 'MATERDEI HOSPITAL' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2023-04-01', NULL, 'active'),
(UUID(), 'CON-055', 'CHRONIC MEDICINES', 'CHRONIC MEDICINES', (SELECT id FROM vendors WHERE name = 'GREENWOOD PHARMACIES' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2024-10-29', NULL, 'active'),
(UUID(), 'CON-056', 'CHRONIC MEDICINE', 'CHRONIC MEDICINE', (SELECT id FROM vendors WHERE name = 'BESTZONE PHARMACY' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2024-10-31', NULL, 'active'),
(UUID(), 'CON-057', 'CHRONIC MEDICINES', 'CHRONIC MEDICINES', (SELECT id FROM vendors WHERE name = 'BOOTIES PHARMACY' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2025-10-29', NULL, 'active'),
(UUID(), 'CON-058', 'CHRONIC MEDICINES', 'CHRONIC MEDICINES', (SELECT id FROM vendors WHERE name = 'MEDORANGE PHARMACIES' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2025-10-29', NULL, 'active'),
(UUID(), 'CON-059', 'AMBULANCE SERVICES', 'AMBULANCE SERVICES', (SELECT id FROM vendors WHERE name = 'DISCOVERY AMBULANCES' LIMIT 1), @service_agreement_id, @managed_care_dept_id, '2025-03-26', NULL, 'active'),
(UUID(), 'CON-060', 'CLEANING SERVICES-CHINHOYI', 'CLEANING SERVICES-CHINHOYI', (SELECT id FROM vendors WHERE name = 'CHACKSEN CLEANING' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-11-01', '2025-10-01', 'active'),
(UUID(), 'CON-061', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'LINDA BANDA ATTORNEYS' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2024-09-01', NULL, 'active'),
(UUID(), 'CON-062', 'CLEANING SERVICES AGREEMENT', 'CLEANING SERVICES AGREEMENT', (SELECT id FROM vendors WHERE name = 'CADCRAFT TRADING (PRIVATE) LIMITED' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-09-01', '2024-08-31', 'active'),
(UUID(), 'CON-063', 'CLEANING SERVICES AGREEMENT', 'CLEANING SERVICES AGREEMENT', (SELECT id FROM vendors WHERE name = 'ANGWISPER ENTERPRISES (PRIVATE) LIMITED' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-04-04', '2025-03-30', 'active'),
(UUID(), 'CON-064', 'CLEANING SERVICES AGREEMENT', 'CLEANING SERVICES AGREEMENT', (SELECT id FROM vendors WHERE name = 'NEMCHEM INTERNATIONAL (PRIVATE) LIMITED' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2025-01-01', '2027-12-31', 'active'),
(UUID(), 'CON-065', 'MEMBERSHIP', 'MEMBERSHIP', (SELECT id FROM vendors WHERE name = 'HURUNGWE RDC' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2021-10-26', '2031-10-25', 'active'),
(UUID(), 'CON-066', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'ZUZE LAW CHAMBERS' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2024-11-01', NULL, 'active'),
(UUID(), 'CON-067', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'VICEMODE INVESTMENTS' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2025-03-01', NULL, 'active'),
(UUID(), 'CON-068', 'BIZTALK PAYMENTS PROCESSING SOLUTION MAINTANANCE SERVUICES AGREEMENT', 'BIZTALK PAYMENTS PROCESSING SOLUTION MAINTANANCE SERVUICES AGREEMENT', (SELECT id FROM vendors WHERE name = 'MACRO-CENTURY (PRIVATE) LIMITED' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-04-01', '2024-03-30', 'active'),
(UUID(), 'CON-069', 'MOU', 'MOU', (SELECT id FROM vendors WHERE name = 'ZIMBABWE UNION FOR JOURNALISTS' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-05-08', '2024-05-07', 'active'),
(UUID(), 'CON-070', 'MOBILE APPLICATION (ADVERTISING)', 'MOBILE APPLICATION (ADVERTISING)', (SELECT id FROM vendors WHERE name = 'VPCG MOBILE' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-05-17', '2024-05-16', 'active'),
(UUID(), 'CON-071', 'LANDSCAPPING SERVICES', 'LANDSCAPPING SERVICES', (SELECT id FROM vendors WHERE name = 'MUNNEX LANDSCAPPING' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-06-28', '2024-05-27', 'active'),
(UUID(), 'CON-072', 'BULK WATER SUPPLY-CHINHOYI', 'BULK WATER SUPPLY-CHINHOYI', (SELECT id FROM vendors WHERE name = 'HIGHMEL SERVICES' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-11-15', '2024-10-15', 'active'),
(UUID(), 'CON-073', 'SECURITY SERVICES FOR GWERU, CHINHOYI, BEITBRIDGE-ADDENDUM', 'SECURITY SERVICES FOR GWERU, CHINHOYI, BEITBRIDGE-ADDENDUM', (SELECT id FROM vendors WHERE name = 'PEACE SECURITY' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-12-18', '2024-11-17', 'active'),
(UUID(), 'CON-074', 'PHONE HANDSETS SLA', 'PHONE HANDSETS SLA', (SELECT id FROM vendors WHERE name = 'PARAGON' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2025-04-01', '2026-03-30', 'active'),
(UUID(), 'CON-075', 'BULK CARDS PRINTING', 'BULK CARDS PRINTING', (SELECT id FROM vendors WHERE name = 'CARDPRO' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-04-14', '2026-04-13', 'active'),
(UUID(), 'CON-076', 'CHIREDZI LEASE AGREEMENT', 'CHIREDZI LEASE AGREEMENT', (SELECT id FROM vendors WHERE name = 'CONCORD HARDWARE CONSTRUCTION/HERBET AND BROTHERS TRANSPORT' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2022-09-01', '2027-08-31', 'active'),
(UUID(), 'CON-077', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'ACFD' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-07-01', NULL, 'active'),
(UUID(), 'CON-078', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'BEST MULTI-PURPOSE CO-OPERATION' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2023-10-01', NULL, 'active'),
(UUID(), 'CON-079', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'CHRIST MINISTRIES HIGH SCHOOL' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2024-10-01', NULL, 'active'),
(UUID(), 'CON-080', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'CHRIST MINISTRIES HIGH SCHOOL' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2024-10-01', NULL, 'active'),
(UUID(), 'CON-081', 'MEMBERSHIP AGREEMENT', 'MEMBERSHIP AGREEMENT', (SELECT id FROM vendors WHERE name = 'ZIMBABWE WOMENS MICROFINANCE BANK' LIMIT 1), @service_agreement_id, @marketing_dept_id, '2021-03-10', NULL, 'active'),
(UUID(), 'CON-082', 'AVAYA PABX SYSTEM', 'AVAYA PABX SYSTEM', (SELECT id FROM vendors WHERE name = 'Frolgate Technology (Private) Limited' LIMIT 1), @service_agreement_id, @ict_dept_id, '2022-03-09', '2027-03-09', 'active'),
(UUID(), 'CON-083', 'PRINTERS RENTAL', 'PRINTERS RENTAL', (SELECT id FROM vendors WHERE name = 'NASHUA' LIMIT 1), @service_agreement_id, @ict_dept_id, '2019-03-20', NULL, 'active'),
(UUID(), 'CON-084', 'CSI & BPI SURVEYS', 'CSI & BPI SURVEYS', (SELECT id FROM vendors WHERE name = 'CONSUMER FEEDBACK CONSULTANCY' LIMIT 1), @service_agreement_id, @strategy_dept_id, '2023-12-05', '2024-03-29', 'active'),
(UUID(), 'CON-085', 'NON DISCLOSURE AGREEMENT', 'NON DISCLOSURE AGREEMENT', (SELECT id FROM vendors WHERE name = 'ZB LIFE ASSURANCE LIMITED' LIMIT 1), @service_agreement_id, @strategy_dept_id, '2018-09-10', NULL, 'active'),
(UUID(), 'CON-086', 'PROVISION OF FUNERAL BENEFIT COVER', 'PROVISION OF FUNERAL BENEFIT COVER', (SELECT id FROM vendors WHERE name = 'ZB LIFE ASSURANCE' LIMIT 1), @service_agreement_id, @strategy_dept_id, '2023-02-01', '2031-01-31', 'active');

-- Display summary
SELECT 
    'Contracts added successfully!' as message,
    COUNT(*) as total_contracts,
    COUNT(DISTINCT vendor_id) as unique_vendors
FROM contracts 
WHERE contract_number LIKE 'CON-%';
